[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=mold"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=mold"]

[target.x86_64-apple-darwin]
rustflags = ["-Clink-arg=-fuse-ld=zld"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

